import AddressObject from "../interfaces/AddressObject";

const masterAddressList: AddressObject[] = [
  {
    street_address1: "SUITE 129 157 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "129",
    street_number: "157",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 121 157 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "121",
    street_number: "157",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1211 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1211",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1207 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1207",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1203 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1203",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1132 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1132",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1131 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1131",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1129 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1129",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1128 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1128",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1127 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1127",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1126 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1126",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1124 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1124",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1122 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1122",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1115 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1115",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1112 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1112",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1111 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1111",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1107 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1107",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1103 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1103",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1032 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1032",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1031 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1031",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1029 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1029",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1028 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1028",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1027 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1027",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1026 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1026",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1024 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1024",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1022 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1022",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1015 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1015",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1012 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1012",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1011 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1011",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1009 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1009",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1007 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1007",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1003 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1003",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 1001 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "1001",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 932 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "932",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 931 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "931",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 929 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "929",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 928 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "928",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 927 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "927",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 926 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "926",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 925 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "925",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 924 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "924",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE 922 155 MERCHANTS' WHARF",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "922",
    street_number: "155",
    street_name: "merchants' wharf",
  },
  {
    street_address1: "SUITE PH09 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "ph",
    unit_type_2: "suite",
    unit_number: "09",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE PH04 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "ph",
    unit_type_2: "suite",
    unit_number: "04",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE PH03 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "ph",
    unit_type_2: "suite",
    unit_number: "03",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE GPH04 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "ph",
    unit_type_2: "suite",
    unit_number: "g04",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE GPH03 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "ph",
    unit_type_2: "suite",
    unit_number: "gph03",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3709 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3709",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3704 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3704",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3703 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3703",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3609 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3609",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3604 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3604",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3603 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3603",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3509 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3509",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3504 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3504",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3503 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3503",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3409 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3409",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3404 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3404",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3403 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3403",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3309 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3309",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3304 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3304",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3303 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3303",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3209 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3209",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3204 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3204",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3203 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3203",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3109 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3109",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3107 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3107",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3105 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3105",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3104 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3104",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3103 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3103",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3101 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3101",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3009 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3009",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3007 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3007",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3005 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3005",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3004 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3004",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3003 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3003",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 3001 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "3001",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 2909 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "2909",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 2907 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "2907",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 2905 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "2905",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 2904 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "2904",
    street_number: "10",
    street_name: "inn on the park drive",
  },
  {
    street_address1: "SUITE 2903 10 INN ON THE PARK DRIVE",
    city: null,
    state: null,
    postal_code: null,
    country: null,
    unit_type_1: "suite",
    unit_number: "2903",
    street_number: "10",
    street_name: "inn on the park drive",
  },
];

export default masterAddressList;
